spring:
  profiles:
    active: dev
  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: false
    show-sql: true
  flyway:
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  boot:
    admin:
      client:
        url: http://127.0.0.1:8081
        instance:
          service-host-type: ip
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 310109923674-la5thl4s4t0b2ajp6acdhq7tra74dn31.apps.googleusercontent.com
            client-secret: GOOGLE
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

logging:
  file:
    name: application.log


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:mem:pw26s-dev
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false
  flyway:
    locations: classpath:/db/prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:pw26s-dev
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:/db/dev
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    locations: classpath:/db/test
