version: "3.9"
########################### SERVICES
services:
  ########################### MINIO
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "minio@admin"
      MINIO_ROOT_PASSWORD: "minio@admin"
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address :9001